class_path: clasp.LinearProbeCLASP
init_args:
  in_features: 512
  num_classes: 5
  dropout: 0.1
  clasp_checkpoint_path: ./logs/CLASP/Emotion_datasets_76acc_42epoch_60M/checkpoints/epoch=41-step=3402.ckpt
  task: emotion

  # LR Scheduler params
  learning_rate: 1e-4
  learning_rate_patience: 10
  LR_sheduler_T_max: 5000
  LR_sheduler_warmup_steps: 1000
  LR_sheduler_min_lr: 2e-5
  LR_sheduler_decay: 0.8
  lr_interval: step